### ISSUE TITLE
vscode theme?

### ISSUE THREAD

**Issue by fictorial** [wadackel/vim-dogrun#12]
Is there a simple way to auto-convert this to a vscode theme?  

It's possible to use https://themes.vscode.one/ and copy and paste all the values from https://github.com/wadackel/vim-dogrun/blob/main/colors/dogrun.vim but yikes.

**Comment by wadackel** [comment]
Hi @fictorial, sorry for late response.

I'm not familiar with the vs code theme, so I don't know how to easily convert dogrun's color scheme 😢
