### ISSUE TITLE
Question: is this how searching/highlighting looks for you too?

### ISSUE THREAD

**Issue by shmup** [wadackel/vim-dogrun#14]
Curious if I should investigate if this is a _me thing_, or maybe just an intentional thing. Either way I'm gonna make adjustments

![image](https://user-images.githubusercontent.com/118710/185028863-a9aa52c5-a72b-41d9-a95c-97461651a5c4.png)

The above is a search for `/background-` and I'm curious if the contrast is as low for y'all as it is for me. Specifically the highlighting of `background`.

Cheers and thanks

**Comment by wadackel** [comment]
Hi @shmup, thank you for your question. And sorry for the late response.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/5393238/188320564-1325af81-c0a5-4a30-9be8-d2df5e91e114.png">

The same highlighting applies to my search results.

For example, I'm thinking of changing the highlighted results to the following, how do you feel :eyes: ?

<img width="779" alt="image" src="https://user-images.githubusercontent.com/5393238/188320545-580d7a83-60dc-4217-a155-209497bea369.png">

**Comment by shmup** [comment]
I think that is a lovely choice, thanks for making a change! <3

I say ship it

**Comment by wadackel** [comment]
Thanks for your valuable input!
I would like to "ship" by adjusting the details :smile:

I'll notify you in this Issue when the changes are completed.

**Comment by wadackel** [comment]
@shmup 

I pushed the changes with https://github.com/wadackel/vim-dogrun/commit/7261253c9a293b9a1e247008964c6cbb860e1700.
Try the latest on the `main` branch when you have time :+1:

**Comment by shmup** [comment]
Looks great! Thanks @wadackel :1st_place_medal: 

![image](https://user-images.githubusercontent.com/118710/188324099-6c7b94ac-101c-47fb-a845-b007dbfdaddb.png)
