### ISSUE TITLE
Invalid character in group name (in colors/dogrun.vim)

### ISSUE THREAD

**Issue by Thaegox** [wadackel/vim-dogrun#15]
Hi,

Right after updating my plugins through vim Plug, I always have the same error coming from `colors/dogrun.vim` :

```vim
line: 93
W18: Invalid character in group name
```

This error happens on all lines between the 93th until line 109 :
```vim
  93   │ hi @string guifg=#7cbe8c ctermfg=108
  94   │ hi @string.regex guifg=#7cbe8c ctermfg=108
  95   │ hi @string.escape guifg=#b871b8 ctermfg=133
  96   │ hi @text.title guifg=#a8a384 ctermfg=144 gui=bold cterm=bold
  97   │ hi @text.reference guifg=#929be5 ctermfg=104
  98   │ hi @text.uri guifg=#545c8c ctermfg=60
  99   │ hi @text.strong gui=bold cterm=bold
 100   │ hi @text.literal guifg=#73c1a9 ctermfg=79
 101   │ hi @parameter guifg=#929be5 ctermfg=104
 102   │ hi @property guifg=#929be5 ctermfg=104
 103   │ hi @keyword guifg=#b871b8 ctermfg=133
 104   │ hi @type guifg=#ac8b83 ctermfg=138
 105   │ hi @type.builtin guifg=#ac8b83 ctermfg=138
 106   │ hi @include guifg=#929be5 ctermfg=104
 107   │ hi @variable.builtin guifg=#ac8b83 ctermfg=138
 108   │ hi @constant.builtin guifg=#73c1a9 ctermfg=79
 109   │ hi @constructor guifg=#9ea3c0 ctermfg=146
 ```

I use vim9 and the latest version of dogrun on arch.

**Comment by wadackel** [comment]
Hi @Thaegox, Thank you for using dogrun :dog:

This seems to be due to the changes we have made for Treesitter.
I will fix it to apply only for Neovim :+1:

**Comment by wadackel** [comment]
@Thaegox 

I made the fixing in commit https://github.com/wadackel/vim-dogrun/commit/7622fa0d300dce9a9223797413b8d4f97417b7b5.
I would appreciate it if you could check if it works when you have time :dog2:

**Comment by Thaegox** [comment]
All good !
Thanks a lot :D

**Comment by wadackel** [comment]
Thanks for your contribution:clap:
I'll close this issue.
