### ISSUE TITLE
invalid character error also on older versions of Neovim

### ISSUE THREAD

**Issue by ds26gte** [wadackel/vim-dogrun#16]
The Neovim on the latest Ubuntu (22.10) shows this error despite your latest fix (7622fa0).

The check for `has("nvim")` simply checks for Neovim but not whether the Neovim version is recent enough. It may be replaced with something like

`has("nvim") && v:version > 800`

**Comment by wadackel** [comment]
Hi @ds26gte, Thank you for your contributing dogrun :dog:

I tried to fix it in commit https://github.com/wadackel/vim-dogrun/commit/c4d049b58b371d795b35f211a677b1cc547780ba.

I am fixing it in a slightly different way than how you advised, but I think it works correctly. I would be glad if you could check the operation when you have time :)

**Comment by ds26gte** [comment]
Thank you! I can confirm your fix works in Nvim 0.7.2.

**Comment by wadackel** [comment]
Thanks for your contribution :dog: :1st_place_medal:
I'll close this issue.
