### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by victorze** [wadackel/vim-dogrun#4]
Currently a python file looks like this:

![original](https://user-images.githubusercontent.com/22132891/72920023-7b929400-3d16-11ea-9dda-0e226c464c89.png)

I suggest these changes:

```vim
" I have this in my .vimrc

" 'yellow': '9b956b'
hi pythonStatement guifg=#9b956b

" 'darkBlue': '4282a0'
hi pythonBuiltin guifg=#4282a0

" 'orange': 'dba99e'
hi pythonDecorator guifg=#dba99e
hi pythonDecoratorName guifg=#dba99e
```

![change](https://user-images.githubusercontent.com/22132891/72920041-81887500-3d16-11ea-9934-7b29914482f4.png)

```python
# I add code for testing
import random
import pygame as pg
from flask import Flask, escape, request

app = Flask(__name__)

@app.route('/')
def hello():
    name = request.args.get("name", "World")
    return f'Hello, {escape(name)}!'

class Map():
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.map = [[0 for x in range(self.width)] for y in range(self.height)]

    def isValid(self, map_x, map_y):
        if (map_x < 0 or map_x >= self.width or
            map_y < 0 or map_y >= self.height):
            return False
        return True
```

**Comment by wadackel** [comment]
HI @victorze 
Thank you for suggestion and example code.
I'll try to make style for it :dog: :+1:

**Comment by wadackel** [comment]
I'm going to apply the following styles to make it look similar to other languages (e.g. TypeScript, Rust, Go etc...). I plan to make the color scheme a little less than the color contrast of your sample :smiley:

![demo](https://user-images.githubusercontent.com/5393238/72991388-42047a80-3e35-11ea-8f52-e68ee6d9ec8d.png)

```rust
hi!(PreProc, purple, -, -, -), // <- Change `PreProc` for` #define`, `include` and` import` colors.
// ...
hi!(pythonStatement, orange, -, -, -),
hi!(pythonBuiltin, cyan, -, -, -),
hi!(pythonRepeat, orange, -, -, -),
hi!(pythonOperator, orange, -, -, -),
hi!(pythonDecorator, pink, -, -, -),
hi!(pythonDecoratorName, pink, -, -, -),
```

What do you think about it ?

**Comment by victorze** [comment]
It looks good, I like it 🐰

**Comment by wadackel** [comment]
thx! I'll push to master after lunch :+1:

**Comment by wadackel** [comment]
@victorze Hi, I pushed to master. Please checkout when you have free-time :dog: 
https://github.com/wadackel/vim-dogrun#filetypes

**Comment by victorze** [comment]
I already checked and everything looks good 👍

**Comment by wadackel** [comment]
Thank you for checking!
I'll close this issue :+1:
