### ISSUE TITLE
Contrast is a bit low when highlight search matches

### ISSUE THREAD

**Issue by lcdsmao** [wadackel/vim-dogrun#5]
<img width="258" alt="Screen Shot 2020-03-07 at 15 42 32" src="https://user-images.githubusercontent.com/13031690/76138347-43f36780-608a-11ea-9b26-7b8deb102dd6.png">

Or maybe I can fix this with some extra settings?

**Comment by wadackel** [comment]
Hi @lcdsmao, Thank you for using `dogrun` :)
Are you using Vim with 256-colors? If so, try using 24bit-colors.

**Comment by lcdsmao** [comment]
Thank you!

**Comment by galmio** [comment]
> Hi @lcdsmao, Thank you for using `dogrun` :)
> Are you using Vim with 256-colors? If so, try using 24bit-colors.

Sorry to open this issue again, but  I'm quite confused on how to enable 24bit color support in Neovim. I've already placed the following in my `.config/nvim/init.vim`
```vim
let $NVIM_TUI_ENABLE_TRUE_COLOR = 1
if (has("termguicolors"))
  set termguicolors
endif
```
However, the selected text looks like the one in the screenshot. I'm using `kitty` with `$TERM=xterm-kitty`
